server:
  servlet:
    context-path: /order-service
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://192.168.0.102:3306/microservices
    username: sandeep
    password: sandeep
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#----------------below logging will activate the jpa transactional log
#actuator endpoint managemnet
management:
  endpoint:
    shutdown:
      enabled: true
    beans:
      enabled: true
    env:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

logging:
  charset:
    file: /opt/tomcat/logs/Orderservice.log
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG